"""Added rating to Vendor model

Revision ID: 7cc7d1e7e902
Revises: a8b0d4d5ba40
Create Date: 2025-04-01 03:10:24.432479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cc7d1e7e902'
down_revision = 'a8b0d4d5ba40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('schedule_time', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.drop_column('schedule_time')
        batch_op.drop_column('schedule_date')

    # ### end Alembic commands ###
